apiVersion: v2
name: external-secrets-crds
description: A Helm chart to manage external-secrets CRDs
version: 1.2.0
appVersion: 1.2.0
maintainers:
  - name: Wiremind
    url: https://github.com/wiremind/wiremind-helm-charts
