apiVersion: v2
name: external-secrets-crds
description: A Helm chart to manage external-secrets CRDs
version: 0.16.0
appVersion: 0.16.0
maintainers:
  - name: Wiremind
    url: https://github.com/wiremind/wiremind-helm-charts
