annotations:
  category: DeveloperTools
apiVersion: v2
name: istio-operator-crds
version: 1.21.0
appVersion: "1.21.0"
description: Manage istio-operator CRDs
keywords:
  - istio
  - operator
  - crds
sources:
  - https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/istio-operator-crds
  - https://github.com/istio/istio/tree/master/operator
engine: gotpl
icon: https://istio.io/latest/favicons/android-192x192.png
maintainers:
  - name: Wiremind
    url: https://github.com/wiremind/wiremind-helm-charts
