{{- if .Values.indexer.enabled }}

{{- range $categoryrName, $categoryValue := .Values.indexer.categories }}

{{- if $categoryValue.autoscaling.enabled }}

{{- if semverCompare ">=1.23-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: autoscaling/v2
{{- else -}}
apiVersion: autoscaling/v2beta2
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "druid.indexer.fullname" (dict "categoryrName" $categoryrName "context" $) }}
spec:
  scaleTargetRef:
    # Only apps/v1 resources are accepted
    apiVersion: apps/v1
    kind: {{ $categoryValue.mode }}
    name: {{ include "druid.indexer.fullname" (dict "categoryrName" $categoryrName "context" $) }}
  minReplicas: {{ $categoryValue.autoscaling.minReplicas }}
  maxReplicas: {{ $categoryValue.autoscaling.maxReplicas }}
  metrics:
    - type: Object
      object:
        metric:
          name: {{ $categoryValue.autoscaling.metricName | default "druid_remaining_tasks_instantaneous" }}
        describedObject:
          apiVersion: "/v1"
          kind: Service
          name: {{ $.Release.Name }}-druid-tasks-exporter
        target:
          type: Value
          value: {{ $categoryValue.autoscaling.targetMetricValue }}
  behavior:
    scaleDown:
      # 5mins is the default value.
      stabilizationWindowSeconds: {{ $categoryValue.autoscaling.scaleDownStabilizationWindowSeconds | default 300 }}

{{- end }}

---

{{- end }}

{{- end }}
