annotations:
  category: DeveloperTools
apiVersion: v2
name: cert-manager-crds
version: 1.16.0
appVersion: "v1.16.0"
description: Manage cert-manager CRDs
keywords:
  - cert
  - manager
  - crds
sources:
  - https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/cert-manager-crds
  - https://github.com/cert-manager/cert-manager
engine: gotpl
icon: https://raw.githubusercontent.com/jetstack/cert-manager/master/logo/logo.png
maintainers:
  - name: Wiremind
    url: https://github.com/wiremind/wiremind-helm-charts
