apiVersion: v1
description: A Helm chart for Kibana
home: https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/kibana
maintainers:
  - name: Wiremind
    url: https://github.com/wiremind/wiremind-helm-charts
name: kibana
version: 8.5.7
appVersion: 8.15.3
sources:
  - https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/kibana
  - https://github.com/elastic/kibana
icon: https://helm.elastic.co/icons/kibana.png
