apiVersion: v2
name: registry
description: A Helm chart for https://github.com/distribution/distribution (OCI registry)
type: application
appVersion: 3.0.0
kubeVersion: ">=1.19.0-0"
version: 0.1.0
maintainers:
  - name: Wiremind
    url: https://github.com/wiremind/wiremind-helm-charts
