{{- if .Values.router.enabled }}

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "druid.router.fullname" . }}-config
  labels:
{{ include "druid.common-labels" . | indent 4 }}
    app.kubernetes.io/component: {{ .Values.router.name }}
data:
  druid_host: {{ include "druid.router.fullname" . }}
  {{- with .Values.router.envVars }}
  {{- toYaml . | nindent 2 }}
  {{- end }}

{{- end }}
