{{- if .Values.router.enabled }}

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "druid.router.fullname" . }}-config
  labels:
{{ include "druid.common-labels" . | indent 4 }}
    app.kubernetes.io/component: {{ .Values.router.name }}
data:
{{ toYaml .Values.router.envVars | indent 2 }}

{{- end }}