apiVersion: v1
name: chartreuse
# NOTE: when setting a development version, please explicitly specify it in e2e test helm chart, otherwise just put *.
appVersion: 5.0.0
version: 5.0.3
description: Automate Alembic SQL schema migrations.
maintainers:
  - name: Wiremind
    url: https://github.com/wiremind/wiremind-helm-charts
sources:
  - https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/chartreuse
  - https://github.com/wiremind/chartreuse
keywords:
  - alembic
  - database
  - migration
  - postgresql
  - clickhouse
