apiVersion: v2
name: istio-operator
version: 1.14.3
appVersion: "1.14.3"
description: Helm chart for deploying Istio operator. This is a carbon-copy of the chart found in https://github.com/istio/istio, with container image versions pinned
keywords:
  - istio
  - operator
sources:
  - https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/istio-operator
  - https://github.com/istio/istio/tree/master/operator
engine: gotpl
icon: https://istio.io/latest/favicons/android-192x192.png
maintainers:
- name: desaintmartin
  email: cdesaintmartin@wiremind.io
- name: machine424
  email: amrini@wiremind.io
- name: maxime1907
  email: 19607336+maxime1907@users.noreply.github.com
