apiVersion: v1
description: A helm chart for Elasticsearch
home: https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/elasticsearch
maintainers:
  - name: Wiremind
    url: https://github.com/wiremind/wiremind-helm-charts
name: elasticsearch
version: 8.15.7
appVersion: 8.15.3
sources:
  - https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/elasticsearch
  - https://github.com/elastic/elasticsearch
icon: https://helm.elastic.co/icons/elasticsearch.png
