apiVersion: v2
name: silence-operator-crds
version: 0.0.2
appVersion: "v0.12.0"
description: Silence operator manages Alertmanager silences via custom resources.
keywords:
  - silence
  - operator
  - crds
sources:
  - https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/silence-operator-crds
  - https://github.com/giantswarm/silence-operator
engine: gotpl
icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
maintainers:
  - name: Wiremind
    url: https://github.com/wiremind/wiremind-helm-charts
