annotations:
  category: DeveloperTools
apiVersion: v2
name: postgres-operator-crds
version: 1.8.0
appVersion: 1.8.0
description: Manage postgres-operator CRDs
keywords:
  - postgres
  - operator
  - crds
sources:
  - https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/postgres-operator-crds
  - https://github.com/zalando/postgres-operator/tree/master/charts/postgres-operator
engine: gotpl
icon: https://raw.githubusercontent.com/zalando/postgres-operator/master/docs/diagrams/logo.png
maintainers:
- name: desaintmartin
  email: cdesaintmartin@wiremind.io
- name: machine424
  email: amrini@wiremind.io
- name: maxime1907
  email: 19607336+maxime1907@users.noreply.github.com
