annotations:
  category: DeveloperTools
apiVersion: v2
name: postgres-operator-crds
version: 1.14.0
appVersion: 1.14.0
description: Manage postgres-operator CRDs
keywords:
  - postgres
  - operator
  - crds
sources:
  - https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/postgres-operator-crds
  - https://github.com/zalando/postgres-operator/tree/master/charts/postgres-operator
icon: https://raw.githubusercontent.com/zalando/postgres-operator/master/docs/diagrams/logo.png
maintainers:
  - name: Wiremind
    url: https://github.com/wiremind/wiremind-helm-charts
