annotations:
  category: DeveloperTools
apiVersion: v2
name: keycloak-operator
version: 0.0.11
appVersion: "18.0.0-legacy"
description: Keycloak is a high performance Java-based identity and access management solution. It lets developers add an authentication layer to their applications with minimum effort.
keywords:
  - keycloak
  - operator
sources:
  - https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/keycloak-operator
  - https://github.com/keycloak/keycloak-operator
engine: gotpl
icon: https://www.keycloak.org/resources/images/keycloak_icon_512px.svg
maintainers:
- name: desaintmartin
  email: cdesaintmartin@wiremind.io
- name: machine424
  email: amrini@wiremind.io
- name: francoisminaud
  email: fminaud@wiremind.io
- name: maxime1907
  email: 19607336+maxime1907@users.noreply.github.com
