apiVersion: v2
name: prometheus-safety-exporter
description: A Helm chart for Kubernetes
type: application
version: 0.2.0
appVersion: "0.6.0"
maintainers:
  - name: Wiremind
    url: https://github.com/wiremind/wiremind-helm-charts
sources:
  - https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/prometheus-safety-exporter
  - https://github.com/pyupio/safety
  - https://safetycli.com/product/safety-cli
keywords:
  - safety
  - python
  - security
