name: cerebro
version: 1.9.11
appVersion: 0.9.4
apiVersion: v2
description: A Helm chart for Cerebro - a web admin tool that replaces Kopf.
home: https://github.com/lmenezes/cerebro
icon: https://github.com/lmenezes/cerebro/blob/master/public/img/logo.png
sources:
  - https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/cerebro
  - https://github.com/lmenezes/cerebro-docker
  - https://github.com/lmenezes/cerebro
maintainers:
  - name: desaintmartin
    email: cdesaintmartin@wiremind.io
  - name: machine424
    email: amrini@wiremind.io
  - name: francoisminaud
    email: fminaud@wiremind.io
