name: cerebro
version: 1.12.0
appVersion: 0.9.4
apiVersion: v2
description: A Helm chart for Cerebro - a web admin tool to manage ElasticSearch
home: https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/cerebro
icon: https://raw.githubusercontent.com/lmenezes/cerebro/main/public/img/logo.png
keywords:
  - cerebro
  - elasticsearch
  - admin
sources:
  - https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/cerebro
  - https://github.com/lmenezes/cerebro-docker
maintainers:
  - name: desaintmartin
    email: cdesaintmartin@wiremind.io
  - name: machine424
    email: amrini@wiremind.io
  - name: francoisminaud
    email: fminaud@wiremind.io
