apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registry.fullname" . }}-config
  labels:
    {{- include "registry.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yml: |
    {{- .Values.config | nindent 4 }}

