apiVersion: v2
description: An Open-Source antivirus engine for detecting trojans, viruses, malware & other malicious threats. Using Mailu docker image.
name: clamav
version: 2.0.0
appVersion: "1.8"
home: https://www.clamav.net
icon: https://www.clamav.net/assets/clamav-trademark.png
sources:
  - https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/clamav
  - https://github.com/Mailu/Mailu/tree/master/optional/clamav
  - https://hub.docker.com/r/mailu/clamav
  - https://github.com/Cisco-Talos/clamav-devel
maintainers:
  - name: desaintmartin
    email: cdesaintmartin@wiremind.io
  - name: machine424
    email: amrini@wiremind.io
  - name: francoisminaud
    email: fminaud@wiremind.io
