apiVersion: v2
appVersion: "1.0"
description: A Helm chart for codekoala/pypi, which uses pypiserver-
name: pypi
version: 0.2.1
icon: https://raw.githubusercontent.com/pypiserver/pypiserver/master/pypiserver_logo.png
maintainers:
- name: desaintmartin
  email: cdesaintmartin@wiremind.io
- name: machine424
  email: amrini@wiremind.io
- name: francoisminaud
  email: fminaud@wiremind.io
