apiVersion: v2
name: silence-operator
version: 0.0.6
appVersion: "0.7.0-7cce53575d94f59a6b5ae7f0a89617117cfc204c"
description: Silence operator manages Alertmanager silences via custom resources.
keywords:
  - silence
  - operator
  - prometheus
  - alertmanager
sources:
  - https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/silence-operator
  - https://github.com/giantswarm/silence-operator
engine: gotpl
icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
maintainers:
- name: desaintmartin
  email: cdesaintmartin@wiremind.io
- name: machine424
  email: amrini@wiremind.io
- name: maxime1907
  email: 19607336+maxime1907@users.noreply.github.com
