# This chart is not made for direct usage, but to be integrated as a subchart.
# Real testing is done in git repository.

resources:
  requests:
    memory: "250Mi"
    cpu: "500m"
  limits:
    memory: "500Mi"
    cpu: "1000m"

fullnameOverride: keycloak-operator-test-release

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 11
  targetCPU: 50
  targetMemory: 50
  labels: {}
  annotations: {}

keycloak:
  adminCredentials:
    username: "admin"
    password: "password"
  ingress:
    enabled: true
    hostname: login-test-release.localhost.dev
    tls: true
    annotations:
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      # Keycloak header with token is bigger than default 4k
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
      nginx.ingress.kubernetes.io/server-snippet: |
        location ~* "^/auth/realms/master/metrics" {
              return 301 /auth/realms/master;
        }
  # Doesnt work
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 11
    targetCPU: 50
    targetMemory: 50
    labels: {}
    annotations: {}

keycloakRealms:
  - realm:
      # General
      name: "Basic"
      displayName: "Basic Realm 1"
      displayNameHtml: "<h1>Basic Realm</h1>"
      emailTheme: "qrm-website"
      loginTheme: "qrm-website"
  - realm:
      # General
      name: "Test"
      displayName: "Test Realm 2"
      displayNameHtml: "<h1>Test Realm</h1>"

keycloakClients:
  - client:
      # Required
      clientId: "clientId_basic"
    realmName: "Basic"
  - client:
      # Required
      clientId: "clientId_test"
    realmName: "Test"

keycloakUsers:
  - user:
      # Required
      username: "realm_user"
      firstName: "John"
      lastName: "Doe"
      email: "user@example.com"
      emailVerified: false
    realmName: "Basic"
  - user:
      # Required
      username: "test_user"
      firstName: "Testing"
      lastName: "Gnitset"
      email: "test@example.com"
      emailVerified: true
    realmName: "Test"
