annotations:
  category: DeveloperTools
apiVersion: v2
name: orc-crds
version: 2.2.0
appVersion: 2.2.0
description: Manage Openstack Resource Controller CRDs
keywords:
  - orc
  - crds
sources:
  - https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/orc-crds
  - https://github.com/k-orc/openstack-resource-controller/
engine: gotpl
maintainers:
  - name: Wiremind
    url: https://github.com/wiremind/wiremind-helm-charts
