apiVersion: v2
name: wiremind-baremetal
description: Helm chart to use BareMetal Encrypted at Rest disks
icon: https://www.wiremind.io/assets/logo.png
version: 1.4.1
appVersion: "3.18.0"
maintainers:
  - name: platform
    email: platform@wiremind.io
