apiVersion: v2
type: application
description: A Helm chart for Karma - an UI for Prometheus Alertmanager
name: karma
home: https://github.com/prymitive/karma
sources:
  - https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/karma
  - https://github.com/prymitive/karma
version: 2.5.1
kubeVersion: ">= 1.19-0"
appVersion: "v0.115"
maintainers:
  - name: Wiremind
    url: https://github.com/wiremind/wiremind-helm-charts
