annotations:
  category: DeveloperTools
apiVersion: v2
name: topolvm-crds
version: 15.9.0
appVersion: 0.39.0
description: Manage topolvm CRDs
keywords:
  - topolvm
  - crds
sources:
  - https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/topolvm-crds
  - https://github.com/topolvm/topolvm/tree/main/charts/topolvm
engine: gotpl
icon: https://i.imgur.com/iqSQEf7.png
maintainers:
  - name: Wiremind
    url: https://github.com/wiremind/wiremind-helm-charts
