apiVersion: v2
name: orc
description: A Helm chart for https://github.com/k-orc/openstack-resource-controller/
type: application
appVersion: v2.3.0
kubeVersion: ">=1.29.0-0"
version: 0.2.1
maintainers:
  - name: Wiremind
    url: https://github.com/wiremind/wiremind-helm-charts
